### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by limelect** [EtheaDev/SVGShellExtensions#1]
I compile with D10.2.3
a lot of missing goodies.
Can you downgrade to D10.2? (in the statements)
So that everybody will enjoy your software.

**Comment by carloBarazzetta** [comment]
Sorry but you need 10.4 to compile this project because I'm using some support for High-DPI introduced in 10.4 like ScaleFactor and CurrentPPI...
In the homepage of the project you can download the installer, it's not necessary to build the project by yourself...
