### ISSUE TITLE
FIle Thumbnails/ICons. *(ARM 64)

### ISSUE THREAD

**Issue by pb5050** [EtheaDev/SVGShellExtensions#10]
any plans of making this arm64 windows compatible

**Comment by pb5050** [comment]
![image](https://user-images.githubusercontent.com/58855947/116018773-63d84880-a608-11eb-94c7-fa6dbe7b3a1c.png)
because most of it works on the Emulation with the WIndows arm64. 

i cant find a working thumbnail viewer for it anywhere at alll.   for windows arm 64 even with emulation .

i am using The surface pro X

**Comment by carloBarazzetta** [comment]
Sorry, but I haven't plan to do this, at the moment.
