### ISSUE TITLE
ver 2.1.0: isn't using Image32 engine

### ISSUE THREAD

**Issue by AngusJohnson** [EtheaDev/SVGShellExtensions#11]
Hi Carlo.
I've just downloaded and tested the SVGShellExtensions Setup binary.
Although there's an option to use Image32 in the SVGShellExtensions setup dialog (and it's enabled by default), it's not rendering preview images as I would expect (ie with filters, masks, text etc).

**Comment by carloBarazzetta** [comment]
You must set Image32 and disable "Prefer Direct 2D"
![image](https://user-images.githubusercontent.com/7803548/127973815-5d168d30-9178-4575-8750-83f5c017fe97.png)

**Comment by AngusJohnson** [comment]
Yes I had done that too 😁.

**Comment by carloBarazzetta** [comment]
I'm fixing default assign to PreferDirect2D to false ;-)

**Comment by AngusJohnson** [comment]
Thanks. Mostly fixed now 😁.
I did have to toggle the Engine to get Image32 to work.
I suspect the radio and checkbox controls aren't properly synchronised with the startup settings.

**Comment by carloBarazzetta** [comment]
yes, at startup the default value of PreferDirect2D was -1 instead of 0 :-(
I've fixed now in 2.2
