### ISSUE TITLE
Compatibility for other file managers

### ISSUE THREAD

**Issue by boromyr** [EtheaDev/SVGShellExtensions#7]
Hi, I tried this great app, and it works perfectly for Windows explorer. I wanted to know if it was possible to add support for XYplorer, which is the most popular alternative to explorer.exe. I tried the preview panel and thumbnails but neither of these works. XYplorer is at 32bit, would it be possible to compile 32-bit SVGShellExtensions? 
Thank you.

**Comment by carloBarazzetta** [comment]
Try with 1.2 version released now!
![image](https://user-images.githubusercontent.com/7803548/109393617-1353b000-7923-11eb-9b3d-6bda890e407e.png)

**Comment by boromyr** [comment]
It works! Perfect thanks a lot!

**Comment by carloBarazzetta** [comment]
You can configure the custom Preview Panel: https://github.com/EtheaDev/SVGShellExtensions/wiki/XYplorer-Support
